export interface ImageCredit {
  usedFor: string;
  title: string;
  author: string;
  source: string;
  license: string;
  licenseUrl: string;
}

/**
 * Every photo on this site (other than IBS's own logo/wordmark) is sourced
 * from Wikimedia Commons, Pexels, or Unsplash under a free license. CC BY-SA
 * requires attribution; the Pexels/Unsplash licenses don't, but sourcing is
 * recorded here for transparency and surfaced on /credits either way.
 */
export const imageCredits: ImageCredit[] = [
  {
    usedFor: "Audio Video & Boardroom Solutions",
    title: "Conference Room Excluzo",
    author: "Excluzobusinesscentre",
    source: "https://commons.wikimedia.org/wiki/File:Conference_Room_Excluzo.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  {
    usedFor: "IT Network & Infrastructure",
    title: "139 Server Room 01",
    author: "Indrajit Das",
    source: "https://commons.wikimedia.org/wiki/File:139_Server_Room_01.jpg",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  {
    usedFor: "Security Solutions",
    title: "Two CCTV security cameras mounted against a blue sky",
    author: "Michal Jakubowski",
    source: "https://unsplash.com/photos/oQD9uq4Rd4I",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Software Licenses",
    title: "Laptop computer",
    author: "Benh Lieu Song",
    source: "https://commons.wikimedia.org/wiki/File:Laptop_computer.jpeg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  {
    usedFor: "Voice Communication",
    title: "IP phone in a data center room",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/17636234/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Call Center Solutions",
    title: "Dual-monitor workstation",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/8204353/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Annual Maintenance Service",
    title: "IT technician working in a data center server room",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/37605911/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Enterprises segment",
    title: "Modern office building interior",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/260994/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Hotels segment",
    title: "Modern hotel lobby interior",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/36354489/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Residential segment",
    title: "Modern living room with smart TV",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/35490296/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "SOHO segment",
    title: "Home office desk setup",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/27436633/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Who We Are (homepage)",
    title: "Engineer monitoring servers in a data center",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/1181316/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    usedFor: "Engineering Process (homepage)",
    title: "Field engineer checking electrical installation",
    author: "Pexels contributor",
    source: "https://www.pexels.com/photo/442160/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  // ── Solution detail page images (Unsplash) ──
  {
    usedFor: "Voice Communication — IP-PBX solution",
    title: "Office desk phones",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1589492477829",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Voice Communication — SIP Phones solution",
    title: "Modern VoIP phone on desk",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1587825140708",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AV & Boardroom — Audio Conferencing solution",
    title: "Conference room microphones and speakers",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1591115765373",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AV & Boardroom — Video Conferencing solution",
    title: "Video conferencing in a boardroom",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1431540015159",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AV & Boardroom — Training Room solution",
    title: "Corporate training room",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1522071820081",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AV & Boardroom — Video Wall solution",
    title: "Multiple screens displaying data",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1519389950473",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AV & Boardroom — PA System solution",
    title: "Auditorium interior",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1475721027785",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AV & Boardroom — Room Booking solution",
    title: "Modern glass meeting room",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1497366216548",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "IT Infrastructure — Data Center solution",
    title: "Modern data center server room",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1558494949",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "IT Infrastructure — Firewall solution",
    title: "Network security equipment",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1563013544",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "IT Infrastructure — Network Rack solution",
    title: "Network server rack",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1558494949",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "IT Infrastructure — Structured Cabling solution",
    title: "Structured cabling with patch panels",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1581092918056",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "IT Infrastructure — Wi-Fi solution",
    title: "Wireless networking equipment",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1563206767",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "IT Infrastructure — Online UPS solution",
    title: "UPS battery backup system",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1620714223084",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Security Solutions — CCTV solution",
    title: "Security cameras on building",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1557597774",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Security Solutions — Access Control solution",
    title: "Access control system",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1558618666",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Security Solutions — Fire Alarm solution",
    title: "Fire alarm control panel",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1605627079912",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Security Solutions — Home Automation solution",
    title: "Smart home control panel",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1558002038",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Call Center — Agent Headsets solution",
    title: "Call center agent with headset",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1588196749597",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Call Center — Gateways solution",
    title: "Telecom network equipment",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1551808525",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Call Center — CRM Dialer solution",
    title: "Data analytics dashboard",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1551288049",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Call Center — Voice Logger solution",
    title: "Network monitoring screens",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1516321318423",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Software Licenses — Collaboration solution",
    title: "Software dashboard on laptop",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1460925895917",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Software Licenses — Creative Apps solution",
    title: "Creative software on monitor",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1517694712202",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "Software Licenses — Security Software solution",
    title: "Cybersecurity software interface",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1563013544",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AMC — Preventive Maintenance solution",
    title: "Technician servicing equipment",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1581092160607",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AMC — Emergency Response solution",
    title: "Field engineer on site",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1621905251189",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
  {
    usedFor: "AMC — Compliance & Documentation solution",
    title: "Maintenance documentation",
    author: "Unsplash contributor",
    source: "https://unsplash.com/photos/1450101499163",
    license: "Unsplash License",
    licenseUrl: "https://unsplash.com/license",
  },
];
